import fs from 'node:fs/promises';
import {load} from 'cheerio';
import {PRIVACY_VERSION_LABEL,PRIVACY_NOTICE_TEXT,PRIVACY_PROCESSING_HTML} from '../src/privacy.js';
const site=JSON.parse(await fs.readFile(new URL('../content/site.json',import.meta.url),'utf8'));
const contactEmail=site.email;
const footer=`<footer><div class="wrap footer"><div class="brand"><span>PX</span><b>PROCELYX</b></div><div><b>Kontakt</b><a href="mailto:${contactEmail}">${contactEmail}</a><a href="tel:+420724796243">+420 724 796 243</a></div><div class="legalLinks"><b>Právní informace</b><a href="/pravni-informace.html">Provozovatel webu</a><a href="/obchodni-podminky.html">Obchodní podmínky</a><a href="/privacy.html">Ochrana osobních údajů a cookies</a></div></div><div class="wrap copy">© 2026 PROCELYX</div></footer>`;
const identity=`<p><strong data-site="founderName">Jaroslav Vojtášek</strong>, <span data-site="businessId">IČO: 48783447</span>, podnikající pod značkou PROCELYX. Fyzická osoba podnikající podle živnostenského zákona, zapsaná v živnostenském rejstříku. Úplné kontaktní údaje jsou na stránce <a href="/pravni-informace.html">provozovatele webu</a>.</p>`;
function page(title,desc,route,body){const version=route==='privacy.html'?PRIVACY_VERSION_LABEL:'23. září 2026';return `<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — PROCELYX</title><meta name="description" content="${desc}"><meta name="robots" content="noindex,follow"><link rel="canonical" href="https://procelyx.cz/${route}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/clanky/article.css"><link rel="stylesheet" href="/polish.css"></head><body><a class="skip" href="#main">Přejít na obsah</a><header><div class="wrap nav"><a class="brand" href="/"><span>PX</span><b>PROCELYX</b></a><div class="actions"><a class="articleBack" href="/">Domů</a><a class="btn sm" href="/#contact">Kontakt</a></div></div></header><main id="main" class="articleBody legalBody"><div class="wrap"><div class="eyebrow">PROCELYX · PRÁVNÍ INFORMACE</div><h1>${title}</h1><p class="legalDate">Verze ze dne ${version}</p>${body}</div></main>${footer}</body></html>`;}
const pages=[
['pravni-informace.html','Provozovatel a pravidla webu','Identifikační údaje provozovatele PROCELYX, kontakt a pravidla používání webových ukázek.',`
<h2>Kdo web provozuje</h2>
<p><strong data-site="founderName">Jaroslav Vojtášek</strong><br><span data-site="businessId">IČO: 48783447</span><br>Značka: PROCELYX<br>Fyzická osoba podnikající podle živnostenského zákona, zapsaná v živnostenském rejstříku.</p>
<p data-business-seat hidden></p>
<p>E-mail: <a href="mailto:${contactEmail}">${contactEmail}</a><br>Telefon: <a href="tel:+420724796243">+420 724 796 243</a><br>Web: <a href="https://procelyx.cz/">procelyx.cz</a></p>
<p>Schůzky probíhají po předchozí dohodě. Na webu není provozována online objednávka ani platební brána. Kontaktní formulář odesílá nezávaznou poptávku.</p>
<h2>Ukázky, články a AI</h2>
<p>Články a diagramy jsou obecné informační materiály. Uvedené příklady, modelové výpočty a demonstrace nepředstavují závazný příslib konkrétní úspory, funkce nebo výsledku ve vaší firmě. Rozsah a přínos konkrétního řešení se ověřují na sjednaném pilotu.</p>
<p>Technická ukázka analýzy poptávky používá předem připravená modelová data. Chat v pravém dolním rohu odpovídá pomocí předem připravených pravidel přímo v prohlížeči; nejde o připojenou generativní AI ani o živou zákaznickou podporu. Text napsaný do tohoto ukázkového chatu se neodesílá provozovateli. Pro skutečnou poptávku použijte kontaktní formulář.</p>
<p>Obsah nenahrazuje individuální právní, daňové, investiční ani jiné regulované odborné poradenství. Před použitím AI výstupu v důležitém rozhodnutí je nutné výstup ověřit příslušnou odbornou osobou. Tato informace neomezuje zákonnou odpovědnost provozovatele.</p>
<h2>Obsah a odkazy</h2>
<p>Texty, fotografie a grafika podléhají právům jejich autorů nebo jiných oprávněných osob. Zákonné užití, například citace za zákonných podmínek, tím není dotčeno. Pro další převzetí obsahu se obraťte na provozovatele. Názvy jiných firem jsou uvedeny jako profesní zkušenost nebo věcná informace; samy o sobě nevyjadřují partnerství či jejich doporučení PROCELYX.</p>
<p>Externí odkazy vedou na samostatné služby s vlastními podmínkami. Jejich otevření není objednávkou služby PROCELYX.</p>
<div class="ctaBox"><h3>Další dokumenty</h3><p><a href="/obchodni-podminky.html">Obchodní podmínky pro firemní spolupráci</a><br><a href="/privacy.html">Ochrana osobních údajů a cookies</a></p></div>`],
['obchodni-podminky.html','Obchodní podmínky','Pravidla sjednání a poskytování konzultací, automatizace a digitálních řešení PROCELYX pro podnikatele.',`
<p>Tyto podmínky upravují individuálně sjednávané konzultace, návrh a zavádění digitálních řešení mezi poskytovatelem a zákazníkem jednajícím v rámci svého podnikání (B2B).</p>${identity}
<h2>1. Kdy podmínky platí</h2>
<p>Podmínky se stanou součástí konkrétní smlouvy, pouze pokud na ně nabídka nebo smlouva výslovně odkáže a zákazník je před uzavřením smlouvy obdrží nebo má možnost se s nimi seznámit a uložit je. Individuální smlouva má přednost. Pozdější změna webu nemění již uzavřenou smlouvu.</p>
<p>Prohlížení webu, vyzkoušení demonstrace ani odeslání poptávky nevytváří placenou objednávku. Automatické potvrzení formuláře potvrzuje pouze přijetí zprávy k odeslání. Závazek vznikne až výslovným přijetím konkrétní nabídky nebo podpisem smlouvy; samotné mlčení přijetím není.</p>
<h2>2. Nabídka, rozsah a cena</h2>
<p>Před zahájením placené práce si strany písemně, například e-mailem, potvrdí rozsah, výstupy, cenu nebo způsob jejího výpočtu, platební podmínky, termíny a součinnost zákazníka. Nabídka uvede i daňový režim a případné náklady na licence, cloud či služby třetích stran. První nezávazná poptávka sama o sobě není zpoplatněna.</p>
<p>Práce nad sjednaný rozsah a nové průběžné náklady vyžadují předchozí dohodu. Není-li určitá integrace, datová migrace, licence, zdrojový kód, průběžný dohled nebo podpora součástí nabídky, nestává se součástí plnění jen tím, že je obecně zmíněna na webu.</p>
<h2>3. Součinnost a bezpečné zavedení</h2>
<p>Zákazník poskytuje včas správné podklady, potřebná oprávnění a kontaktní osobu pro rozhodování. Zajišťuje oprávnění k použití předaných dat a podkladů. Přístupy se předávají dohodnutým bezpečným způsobem s nezbytným rozsahem oprávnění.</p>
<p>Před zásahem do produkčního systému strany určí zálohování, testovací postup, schvalování a případný návrat k předchozí verzi. Zákazník zajišťuje vlastní běžné zálohy, pokud jejich zajištění výslovně nepřevzal poskytovatel. Chybějící součinnost může ovlivnit termín; poskytovatel na překážku a její dopad bez zbytečného odkladu upozorní.</p>
<h2>4. Pilot, předání a vady</h2>
<p>Pilot slouží k ověření dohodnutých předpokladů v omezeném rozsahu. Produkční provoz a další rozšíření vyžadují dohodu. Způsob předání, ověření a přijetí výstupu si strany určí podle typu zakázky. Mlčení zákazníka samo o sobě není potvrzením bezvadnosti.</p>
<p>Poskytovatel plní s odbornou péčí a odpovídá za vady podle smlouvy a právních předpisů. Zjištěnou vadu oznamte bez zbytečného odkladu na <a href="mailto:${contactEmail}">${contactEmail}</a> s popisem projevu a podmínkami jejího vzniku. Strany dohodnou přiměřený způsob a termín nápravy; tím se neomezují zákonná práva z vadného plnění.</p>
<h2>5. AI, očekávaný přínos a jiné služby</h2>
<p>AI může vytvářet nepřesné nebo neúplné výstupy. Pro citlivá rozhodnutí musí sjednané řešení obsahovat odpovídající lidskou kontrolu. Bez zvláštního písemného ujednání poskytovatel neslibuje konkrétní obchodní výsledek, procento úspory, bezchybnost všech AI odpovědí ani nepřetržitou dostupnost.</p>
<p>Dostupnost a pravidla samostatných služeb třetích stran se řídí jejich podmínkami. Poskytovatel odpovídá za vlastní sjednané plnění a odbornou péči při integraci; tento článek jej nezbavuje odpovědnosti za vlastní chybu. Podstatné změny externí služby a jejich dopad řeší strany dohodou.</p>
<h2>6. Odpovědnost</h2>
<p>Odpovědnost za újmu se řídí českým právem. Strany přijímají přiměřená opatření k předcházení škodám a bez zbytečného odkladu se informují o závažném riziku.</p>
<p><strong>Případný finanční limit náhrady škody musí být zvlášť výslovně sjednán v konkrétní B2B smlouvě.</strong> Samotné zveřejnění těchto podmínek žádný limit nezavádí. Při jeho sjednání je třeba zohlednit cenu, rizika zakázky, pojištění a postavení obou stran.</p>
<p>Žádné ujednání nevylučuje ani neomezuje odpovědnost v případech, kdy to zákon nepřipouští, zejména za újmu na přirozených právech člověka, újmu způsobenou úmyslně nebo hrubou nedbalostí ani právo slabší strany na náhradu újmy (§ 2898 občanského zákoníku).</p>
<h2>7. Práva k výstupům a důvěrnost</h2>
<p>Rozsah licence, předání zdrojových kódů, možnost úprav a dalšího užití sjednají strany v nabídce nebo smlouvě. Práva zákazníka k jeho vstupním datům zůstávají zachována. Práva k samostatným nástrojům a knihovnám třetích stran se řídí příslušnými licencemi.</p>
<p>Strany chrání neveřejné informace získané při spolupráci a použijí je pouze k jejímu účelu, pokud zákon nevyžaduje jinak. Zákaznická data neslouží bez samostatné dohody k trénování veřejných AI modelů. Konkrétní AI dodavatele a nastavení jejich práce s daty strany určí před zapojením do zakázky.</p>
<p>Pokud má poskytovatel zpracovávat osobní údaje jménem zákazníka, uzavřou strany před zahájením takového zpracování odpovídající zpracovatelskou smlouvu. <a href="/privacy.html">Informace k poptávkovému formuláři</a> takovou smlouvu nenahrazují.</p>
<h2>8. Ukončení a řešení sporu</h2>
<p>Možnosti ukončení, vypořádání rozpracované práce a předání dat se řídí konkrétní smlouvou a zákonem. Při ukončení strany vyúčtují řádně poskytnuté a sjednané plnění. Zákonné důvody odstoupení zůstávají zachovány.</p>
<p>Smlouvy se řídí právem České republiky. Případný spor se strany nejprve pokusí vyřešit dohodou; není-li to možné, rozhodne příslušný soud podle právních předpisů.</p>
<h2>9. Pokud jednáte jako spotřebitel</h2>
<p>Tyto B2B podmínky se nepoužijí k omezení práv spotřebitele. Ozvěte se před sjednáním služby, pokud ji objednáváte mimo své podnikání. Před případným uzavřením spotřebitelské smlouvy dostanete samostatné informace o ceně, poskytování služby, reklamaci, právu na odstoupení a mimosoudním řešení sporů. Na tomto webu se spotřebitelské objednávky přímo neuzavírají.</p>`],
['privacy.html','Ochrana osobních údajů a cookies','Jak PROCELYX zpracovává poptávky, komu předává údaje, jak dlouho je uchovává a jak uplatnit svá práva.',`
<h2>1. Správce a kontakt</h2>${identity}
<p>Ve věcech ochrany údajů napište na <a href="mailto:${contactEmail}">${contactEmail}</a> nebo zavolejte <a href="tel:+420724796243">+420 724 796 243</a>. Správce nejmenoval pověřence pro ochranu osobních údajů.</p>
<h2>2. Jaké údaje a proč zpracováváme</h2>
<ul><li><strong>Poptávka a domluva spolupráce:</strong> jméno, e-mail a text zprávy; dobrovolně také firma nebo projekt, telefon a vybraná oblast. Spolu s poptávkou se uloží stránka, ze které byla odeslána, a pokud jsou k dispozici, také odkazující web a parametry kampaně (viz část 6). Údaje slouží k odpovědi, upřesnění potřeby a přípravě nabídky. Pokud poptáváte službu pro sebe, právním základem jsou kroky před uzavřením smlouvy na vaši žádost (čl. 6 odst. 1 písm. b GDPR). U kontaktních osob firem jde o oprávněný zájem na vyřízení obchodního jednání (písm. f).</li>
<li><strong>Rezervace schůzky:</strong> pokud využijete odkaz na Microsoft Bookings, vyplníte tam své jméno, e-mail, vybraný termín a případnou poznámku. Údaje slouží k domluvě a uskutečnění schůzky; právní základ je stejný jako u poptávky. Rezervace je dobrovolná, můžete místo ní použít e-mail nebo formulář na našem webu.</li>
<li><strong>Sjednaná spolupráce:</strong> kontaktní a smluvní údaje zpracováváme pro plnění smlouvy, související zákonné povinnosti a ochranu právních nároků (čl. 6 odst. 1 písm. b, c a f GDPR).</li>
<li><strong>Bezpečnost webu:</strong> poskytovatel infrastruktury zpracovává technické údaje požadavku, například IP adresu, čas, požadovanou URL a údaje o prohlížeči. IP adresa slouží také k omezení četnosti odeslání. Účelem a oprávněným zájmem je ochrana dostupnosti webu a prevence zneužití (čl. 6 odst. 1 písm. f GDPR).</li></ul>
<p>Vyplnění formuláře je dobrovolné. Povinná pole jsou potřebná pro jeho vyřízení; bez nich formulář nelze odeslat. Můžete nás místo toho kontaktovat e-mailem nebo telefonicky. Odesláním poptávky se nepřihlašujete k newsletteru a nedáváte souhlas s reklamou.</p>
<h2>3. Kam zpráva putuje</h2>
<p>Formulář přijímá náš serverový endpoint na Cloudflare. Zprávu do firemní schránky odesílá Google Workspace prostřednictvím naší aplikace Google Apps Script; jako záložní způsob doručení je připravena služba Resend. Vaše adresa se nastaví jako adresa pro odpověď. ${PRIVACY_PROCESSING_HTML} Pro omezení duplicit se ukládá technický otisk požadavku, čas a stav odeslání. Otisk platí 24 hodin a po uplynutí této doby se odstraňuje při dalším zpracování. Obsah formuláře nevypisujeme do aplikačních logů. Sledování otevření a kliknutí v odesílaných e-mailech je vypnuté.</p>
<p>Odkaz pro rezervaci vede na samostatnou službu Microsoft Bookings. Rezervace se ukládá do pracovního kalendáře Jaroslava Vojtáška v prostředí Microsoft 365 organizace ARKANCE (doména arkance.world). K údajům mohou mít podle nastavení této organizace přístup její správci a mohou se na ně vztahovat její pravidla uchování. Pozvánka na online schůzku se odešle prostřednictvím Microsoft Teams. Do poznámky k rezervaci nevkládejte důvěrné podklady; pro jiný způsob domluvy použijte kontaktní formulář nebo e-mail PROCELYX.</p>
<p>Technickými zpracovateli a příjemci v nezbytném rozsahu jsou zejména Cloudflare (provoz a zabezpečení webu) a Google Workspace včetně Apps Script (odesílání a firemní pošta); při využití záložního odesílání také Resend / Plus Five Five, Inc. (transakční e-mail). Při navazující zakázce mohou údaje získat také účetní, právní poradci nebo příslušné orgány, je-li to potřebné pro zákonnou povinnost nebo ochranu práv.</p>
<p>Dodavatelé působí také mimo Evropský hospodářský prostor, zejména v USA. Jejich zpracovatelské podmínky upravují mezinárodní předávání prostřednictvím odpovídajících záruk, zejména standardních smluvních doložek Evropské komise; kde se použije rozhodnutí o odpovídající ochraně, postupují podle něj. Zvolený evropský region odesílání e-mailu neznamená, že veškeré zpracování probíhá pouze v EU.</p>
<p>Podrobnosti a záruky: <a href="https://www.cloudflare.com/cloudflare-customer-dpa/">Cloudflare DPA</a>, <a href="https://resend.com/legal/dpa">Resend DPA</a> a <a href="https://workspace.google.com/terms/dpa_terms.html">Google Workspace DPA</a>. Informace nebo kopii relevantních záruk lze vyžádat na našem kontaktním e-mailu.</p>
<h2>4. Doba uchování</h2>
<ul><li>Poptávky, z nichž nevznikne spolupráce, uchováváme nejdéle 12 měsíců od posledního věcného kontaktu, pokud není třeba nezbytná část pro doložený právní nárok.</li><li>Dokumentaci sjednané spolupráce uchováváme po dobu smlouvy a následně zpravidla 3 roky k ochraně právních nároků. Probíhající spor nebo zvláštní zákonná povinnost mohou vyžadovat delší dobu; potom zůstane pouze potřebný rozsah.</li><li>Daňové a účetní doklady uchováváme po zákonnou dobu odpovídající druhu dokladu a právnímu postavení správce, nikoli automaticky celou poptávku.</li><li>Technické záznamy u poskytovatelů infrastruktury a e-mailu se uchovávají podle jejich nastavených provozních a bezpečnostních lhůt. Délka se odvíjí od typu záznamu a používaného tarifu; údaje nepoužíváme pro profilování. Při oprávněné žádosti o výmaz zohledníme také relevantní kopie u zpracovatelů a jejich cyklus mazání záloh.</li></ul>
<h2>5. Vaše práva</h2>
<p>Za podmínek GDPR máte právo na přístup k údajům a jejich kopii, opravu, výmaz, omezení zpracování a přenositelnost tam, kde se uplatní. <strong>Proti zpracování na základě oprávněného zájmu můžete vznést námitku.</strong> Tato práva nejsou neomezená, například zákonná povinnost může bránit okamžitému výmazu.</p>
<p>Žádost vyřídíme bez zbytečného odkladu, zpravidla do jednoho měsíce. Případné zákonné prodloužení a důvody vám v této lhůtě sdělíme. Je-li to nutné, přiměřeně ověříme totožnost žadatele. Máte také právo podat stížnost u <a href="https://uoou.gov.cz/">Úřadu pro ochranu osobních údajů</a>, Pplk. Sochora 27, 170 00 Praha 7.</p>
<p>Formulář není založen na souhlasu. Pokud bychom v budoucnu pro jiný účel žádali o samostatný souhlas, půjde jej kdykoli odvolat bez vlivu na zákonnost předchozího zpracování. Na tomto webu neprobíhá automatizované rozhodování s právními nebo obdobně významnými účinky ani profilování.</p>
<h2 id="cookies">6. Cookies a uložení v prohlížeči</h2>
<p>Web neobsahuje reklamní pixely, analytické měření návštěvníků ani vložená videa či externí fonty. Nepoužívá vlastní analytické nebo marketingové cookies. Technická infrastruktura může používat nezbytné bezpečnostní mechanismy pro ochranu před útoky.</p>
<p>Volbu češtiny nebo angličtiny ukládáme do <code>sessionStorage</code> pod klíčem <code>pxlang</code>, pouze pro fungování jazykové preference v dané kartě. Standardně zanikne po ukončení relace karty; některé prohlížeče mohou relaci obnovit. Údaj se neposílá na server. Zablokování úložiště nezabrání čtení webu ani odeslání poptávky, jen se nemusí zapamatovat jazyk.</p>
<p>Pokud na web přijdete z jiného webu nebo z odkazu s parametry kampaně (<code>utm_source</code>, <code>utm_medium</code>, <code>utm_campaign</code>, <code>utm_content</code>, <code>utm_term</code>), uložíme tyto parametry a adresu odkazující stránky bez jejích parametrů do <code>sessionStorage</code> pod klíčem <code>pxsrc</code>, rovněž jen po dobu relace karty. Na server se odešlou pouze spolu s odeslanou poptávkou, abychom věděli, odkud poptávka přišla. Nepoužíváme je k měření návštěvnosti ani ke sledování návštěvníků.</p>
<p>Ukázkový chat a technická simulace pracují pouze v paměti stránky a nepřenášejí zadané údaje na server. Skutečný kontaktní formulář naopak zprávu odešle až po stisku tlačítka „Odeslat poptávku“. Pro uvedené nezbytné funkce nezobrazujeme souhlasovou lištu. Před případným přidáním nepovinného sledování zajistíme odpovídající volbu souhlasu a aktualizujeme tyto informace.</p>
<h2>7. Bezpečné sdílení podkladů</h2>
<p>Do formuláře ani ukázkového chatu nevkládejte hesla, přístupové klíče, zdravotní či jiné zvlášť citlivé údaje nebo důvěrnou zákaznickou dokumentaci. Bezpečné předání podkladů a pravidla případného dalšího zpracování domluvíme individuálně.</p>`]
];
for(const [route,title,desc,body] of pages)await fs.writeFile('public/'+route,page(title,desc,route,body));
// Keep legal information reachable from every public page.
for(const name of (await fs.readdir('public',{recursive:true})).filter(x=>x.endsWith('.html'))){
 const file='public/'+name,$=load(await fs.readFile(file,'utf8'));
 if($('#leadForm').length){
  $('.consent').replaceWith(`<p class="formPrivacy" data-t="formPrivacy">${PRIVACY_NOTICE_TEXT}</p>`);
  $('footer .footer > div').last().addClass('legalLinks').find('a[href$="privacy.html"]').text('Ochrana údajů a cookies');
  if(!$('footer a[href="/obchodni-podminky.html"]').length)$('footer .legalLinks').append('<a href="/pravni-informace.html" data-t="legalOperator">Provozovatel webu</a><a href="/obchodni-podminky.html" data-t="legalTerms">Obchodní podmínky</a>');
 }else if(!$('.legalLinks').length){
  if($('footer .footer').length)$('footer .footer').append('<div class="legalLinks"><b>Právní informace</b><a href="/pravni-informace.html">Provozovatel webu</a><a href="/obchodni-podminky.html">Obchodní podmínky</a><a href="/privacy.html">Ochrana údajů a cookies</a></div>');
  else $('body').append(footer);
 }
 await fs.writeFile(file,$.html());
}
console.log('Legal pages and navigation updated. Registered seat is populated only from approved site configuration.');
